version: '3.5'
services:
  db:
    image: mysql:8.0.22
    environment:
      - MYSQL_ROOT_PASSWORD=elql1004
      - MYSQL_DATABASE=airbnb
      - MYSQL_USER=suntory
      - MYSQL_PASSWORD=elql1004
    ports:
      - 3307:3306

  app:
    image: deploy-test:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3307/airbnb?useSSL=false
    depends_on:
      - db

